- id: '1603104774444'
  alias: Reset all speakers to 20% at 5AM
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    entity_id: media_player.master_bedroom_speaker
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    entity_id: media_player.den_speaker
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    entity_id: media_player.kitchen_display
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    entity_id: media_player.kitchen_speaker
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    entity_id: media_player.living_room_speaker
  mode: single
- id: '1605631963494'
  alias: Turn on Living Room lights when the Sun sets
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:10:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '10:00:00'
    before: '18:00:00'
  action:
  - service: light.turn_on
    entity_id: light.living_room
    data:
      transition: 1800
      brightness_pct: 100
      kelvin: 5000
  mode: single
- id: '1606954991169'
  alias: Turn on Living Room at 6:20am unless sun has risen
  description: ''
  trigger:
  - platform: time
    at: 06:20:00
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    entity_id: light.living_room
    data:
      transition: 300
      brightness_pct: 50
      kelvin: 5000
  mode: single
- id: '1607012698226'
  alias: Turn off Living Room lights at 9am if TV is off
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - type: is_off
    condition: device
    device_id: bdc2a1809e9821bb184d6048cdeeffc1
    entity_id: binary_sensor.living_room_tv
    domain: binary_sensor
  action:
  - domain: light
    entity_id: light.table
    device_id: 9124eff611d38257570c7d4b8c7cdefc
    type: turn_off
  - domain: light
    entity_id: light.corner_light
    device_id: b76c89e4d08a75606b24486e84dcf3ed
    type: turn_off
  - domain: light
    entity_id: light.tv_light
    device_id: 97b179a6266f8042e90c9bd003286203
    type: turn_off
  mode: single
- id: notify_if_batteries_are_low
  alias: Notification - Alert That Batteries Are Low
  trigger:
  - platform: time
    at: '19:00:00'
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: "{% set min_battery_level = 30 -%} {% set ns = namespace(found=false)\
        \ -%} {% for entity_id in states.group.battery_levels.attributes.entity_id\
        \ -%}\n  {% set parts = entity_id.split('.') -%}\n  {% if (states(entity_id)\
        \ | replace(\"%\",\"\") | int) < min_battery_level -%}\n    {% set ns.found\
        \ = true -%}\n  {% endif -%}\n{% endfor -%} {{ ns.found }}\n"
  action:
  - service: notify.mobile_app_oneplus_a6013
    data_template:
      message: "{%- set min_battery_level = 30 -%} {%- for entity_id in states.group.battery_levels.attributes.entity_id\
        \ -%}\n  {%- set parts = entity_id.split('.') -%}\n  {%- if (states(entity_id)\
        \ | replace(\"%\",\"\") | int) < min_battery_level -%}\n    {{ states[parts[0]][parts[1]].name\
        \ }} battery level is {{ states(entity_id) }}.{{ '\\n' }}\n  {%- endif -%}\n\
        {%- endfor -%}\n"
  mode: single
- id: '1608594217891'
  alias: Turn off Living Room lights at midnight if TV is off
  description: ''
  trigger:
  - platform: time
    at: '23:59:59'
  condition:
  - type: is_off
    condition: device
    device_id: bdc2a1809e9821bb184d6048cdeeffc1
    entity_id: binary_sensor.living_room_tv
    domain: binary_sensor
  action:
  - domain: light
    entity_id: light.table
    device_id: 9124eff611d38257570c7d4b8c7cdefc
    type: turn_off
  - domain: light
    entity_id: light.corner_light
    device_id: b76c89e4d08a75606b24486e84dcf3ed
    type: turn_off
  - domain: light
    entity_id: light.tv_light
    device_id: 97b179a6266f8042e90c9bd003286203
    type: turn_off
  mode: single
- id: '1613562670502'
  alias: Turn off bedroom switches at 10am on weekdays
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: switch.turn_off
    entity_id:
    - switch.kettle
    - switch.my_charger
    - switch.bedroom_lamp
  mode: single
