# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: 'en-uk'
  
# flux
switch:
  - platform: flux
    lights:
      - light.den_lamp
    start_colortemp: 5500
    sunset_colortemp: 5500
    stop_colortemp: 2500
    start_time: '7:00'
    stop_time: '23:00'
    brightness: 255
    
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_project_id
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriber_id

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
