---
platform: custom
lambda: |-
  auto my_sensor = new DHT22MQTTSensor();
  my_sensor->mqttPassword = (char*)"$mqtt_password";
  //my_sensor->mqttChannel = "$mqtt_channel";
  my_sensor->apikey = "$mqtt_api";
  App.register_component(my_sensor);
  return {my_sensor->temperature_sensor, my_sensor->humidity_sensor, my_sensor->heat_index};

sensors:
  - name: "$upper_devicename Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
  - name: "$upper_devicename Humidity"
    unit_of_measurement: "%"
    accuracy_decimals: 1
    icon: mdi:water-percent
  - name: "$upper_devicename Heat Index"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
