#
# garage (nodemcu_2): Garage temperature sensor
# 
# This ESPHome code is used on a nodemcu esp8266.
# It does temperature sensing in the Garage
#
# It has 3 outputs:
# Garage Temperature
# Garage Humidity
# Garage Heat Index
#
# Climate sensing is done by a DHT22 and handled by a custom sensor every 60 seconds,
# data is also uploaded to Thingspeak
#
substitutions:
  devicename: "garage"
  upper_devicename: "Garage"
  mqtt_password: !secret mqtt_password
  mqtt_channel: !secret garage_mqtt_channel
  mqtt_api: !secret garage_mqtt_api
  
esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  includes:
    - dht22_mqtt.h
  libraries:
    - "DHT sensor library"
    - "PubSubClient"
    - 'Adafruit Unified Sensor'

<<: !include common/common.yaml
<<: !include common/logger.yaml

sensor:
- !include common/sensor/dht22.yaml
- !include common/sensor/uptime.yaml

binary_sensor:
- !include common/binary_sensors/status.yaml

switch:
- !include common/switch/restart.yaml

text_sensor:
- !include common/text_sensor/version.yaml
- !include common/text_sensor/wifi_info.yaml
