#
# living_room (nodemcu_1): Living Room temperature sensor and TV ping
#
# This ESPHome code is used on a nodemcu esp8266.
# It does temperature sensing and detects the on/off status of the Living Room TV
#
# It has 4 outputs:
# Living Room Temperature
# Living Room Humidity
# Living Room Heat Index
# Living Room TV
#
# Climate sensing is done by a DHT22 and handled by a custom sensor every 60 seconds,
# data is also uploaded to Thingspeak
#
# TV Status sensing is done by a custom ping sensor run every 15 seconds
#
substitutions:
  devicename: "living_room"
  upper_devicename: "Living Room"
  mqtt_password: !secret mqtt_password
  mqtt_channel: !secret living_room_mqtt_channel
  mqtt_api: !secret living_room_mqtt_api
  tv_ip_address: !secret tv_ip_address

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
  includes:
    - dht22_mqtt.h
    - Ping.h
  libraries:
    - "DHT sensor library"
    - "PubSubClient"
    - "ESP8266Ping"
    - "Adafruit Unified Sensor"

<<: !include common/common.yaml
<<: !include common/logger.yaml

sensor:
- !include common/sensor/dht22.yaml

binary_sensor:
- !include common/binary_sensors/ping.yaml