substitutions:
  mqtt_password: !secret mqtt_password
  mqtt_channel: !secret garage_mqtt_channel
  mqtt_api: !secret garage_mqtt_api
  
esphome:
  name: garage
  platform: ESP8266
  board: nodemcuv2
  includes:
    - temp_mqtt.h
  libraries:
    - "DHT sensor library"
    - "PubSubClient"
    - 'Adafruit Unified Sensor'

wifi:
  ssid: !secret wifi_ssid_1
  password: !secret wifi_pwd_1
  #use_address: nodemcu_4.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu 4 Fallback Hotspot"
    password: !secret fallback_pwd

captive_portal:

# Enable logging
logger:
  level: !secret debug_level
  esp8266_store_log_strings_in_flash: !secret debug_esp8266_store_log_strings_in_flash

# Enable Home Assistant API
api:
  password: !secret ha_api_pwd

ota:
  password: !secret ota_api_pwd
    
web_server:
  port: 80

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyCustomSensor();
    my_sensor->mqttPassword = (char*)"$mqtt_password";
    my_sensor->mqttChannel = "$mqtt_channel";
    my_sensor->apikey = "$mqtt_api";
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor, my_sensor->humidity_sensor, my_sensor->heat_index};

  sensors:
  - name: "Garage Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - name: "Garage Humidity"
    unit_of_measurement: "%"
    accuracy_decimals: 1
  - name: "Garage Heat Index"
    unit_of_measurement: "°C"
    accuracy_decimals: 1